language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
services:
  - docker
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm test
  - npm run build:dev
  - npm run build:prod
cache: yarn
sudo: required
